version: '2'
services:
    application:
        build:
          context: .
          dockerfile: Dockerfile
          args:
            IS_DEV_MODE: 1
        environment:
          - DB_HOST=mysql
          - MYSQL_PASSWORD=root
          - MYSQL_USER=joe
          - MYSQL_DATABASE=joe
          - MYSQL_PASSWORD=joe
          - APPLICATION_LIVE=1
          - API_DOMAIN=lumen.local
          - APP_DEBUG=1
        env_file:
            - images/php/main.env
            - images/php/newrelic.env
